### ISSUE TITLE
TLS Redirect Not Working on Every Page

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1148] opened 2021-05-29 13:45 UTC
I just noticed that particular pages on the 360 site do not change http:// to https:// when you enter the url directly. See, for example, when you type "360.Gordon.edu/about" into a safari mobile browser. The url is not secure and does not fix itself as you navigate through the rest of the site.
![image](https://user-images.githubusercontent.com/43764277/120072598-3264f980-c05a-11eb-8526-1fb056b70226.jpeg)

All of our pages should be https:// , especially because we handle Gordon authentication and some PII on our pages.

**Comment by EjPlatzer** [comment] 2021-05-29 13:49
This looks like a duplicate of #332 so I'm going to close it.

**Closed by EjPlatzer** 2021-05-29 13:49 UTC

**Comment by bennettforkner** [comment] 2021-05-29 14:49
Yeah sorry I thought I knew the board well enough! 😬
