### ISSUE TITLE
Big Bug - Hitting 'Include Alumni' and search crashes user browser

### ISSUE THREAD

**Issue by Matt-Ramos** [gordon-cs/gordon-360-ui#798] opened 2020-06-26 19:07 UTC
Log in to faculty test (even on live 360) > people > check include alumni and press search > ......

**Comment by EjPlatzer** [comment] 2021-01-29 19:23
This is not a bug as much as a design issue. Searching with only includeAlumni enabled will attempt to retrieve and display EVERY person visible to 360, including students, FacStaff, and all alum in the database. Understandably, the browser cannot handle mounting that many components at once.

A solution would probably involve pagination and lazy loading results so that the front end is only dealing with a subset of search results at once. This would allow for the page to still load quickly for smaller result sets while being able to handle excessive results more robustly.

**Comment by EjPlatzer** [comment] 2021-06-29 13:39
Closed by #1207 although the underlying issue of loading too many results at once is not fixed, just the behavior of doing an empty (i.e. all-inclusive) search when none of the search fields had meaningful entries.

**Closed by EjPlatzer** 2021-06-29 13:39 UTC
Labels: Enhancement, Modification, Search
