### ISSUE TITLE
Add residence hall room to "Residence" in Profile

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#1487] opened 2022-08-22 18:04 UTC
For staff users only (fac/staff/GoPo/RD/Admins).
Allows for urgent targeted lookups for students or roommates in a hall. Dorm rosters don't allow, and RD's have asked for this improvement.
I realize the account permissions model has changed, so I'm not sure the proper way to describe how to move forward.

**Comment by EjPlatzer** [comment] 2022-08-22 18:08
This looks like a duplicate of #1379. I'm closing this issue so we can build from the discussion there.

**Closed by EjPlatzer** 2022-08-22 18:08 UTC
Labels: Modification, Privacy
