### ISSUE TITLE
Image field for Group Pages

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#734] opened 2020-05-21 14:36 UTC
Add image to the group roster and group leaders

**Comment by roddy3** [comment] 2021-06-04 14:45
@Davideo37, here is the project.

**Comment by roddy3** [comment] 2021-06-09 17:31
Pictures of the Leaders/Advisor of the group next to their names, see an example below  



![Screen Shot 2021-06-09 at 1 23 02 PM](https://user-images.githubusercontent.com/60272749/121400744-efdad100-c925-11eb-81c3-03079869a54d.png)



Have a place where they can share their past important events, and also their about/origins pretty much similar to what 360 has see example below



![Screen Shot 2021-06-09 at 1 29 49 PM](https://user-images.githubusercontent.com/60272749/121401608-e43bda00-c926-11eb-8240-d3c174a83dd5.png)

**Comment by Davideo37** [comment] 2021-06-09 17:38
After hearing feedback from a couple of the club leaders, we also discovered a couple UI

> 
> 
> Pictures of the Leaders/Advisor of the group next to their names, see an example below
> 
> ![Screen Shot 2021-06-09 at 1 23 02 PM](https://user-images.githubusercontent.com/60272749/121400744-efdad100-c925-11eb-81c3-03079869a54d.png)
> 
I made a separate issue for this #1182

**Comment by roddy3** [comment] 2021-06-09 18:27
Thanks you @Davideo37

**Comment by roddy3** [comment] 2021-07-09 19:56
Duplicate of #1182

**Closed by roddy3** 2021-07-09 19:56 UTC
Labels: Feature, Involvements, Modification
